In [2]:
import pandas as pd

In [3]:
first = pd.read_csv("/home/buchalova/school/plASgraph2/results/eval_original_scripts/summary_no_normalization.csv")     # lr = [0.0001,0.0003,0.005]
second = pd.read_csv("/home/buchalova/school/plASgraph2/results/eval_original_scripts/summary_with_normalization.csv")  # lr = [0.0001,0.0003,0.005]
third = pd.read_csv("/home/buchalova/school/plASgraph2/results/eval_original_scripts/summary_combination.csv")          # lr = [0.001,0.003]

In [3]:
first

,mol_type,method,contigs,real,predicted,auc,precision,recall,f1,accuracy
0,chrom,1_h_lr_0.0001_tie_False_norm_None,38272,34298,36203,0.893120,0.926137,1.000000,0.947228,0.907294
1,chrom,1_h_lr_0.0001_tie_True_norm_None,38272,34298,38218,0.847683,0.890142,1.000000,0.940428,0.887556
2,chrom,1_h_lr_0.0003_tie_False_norm_None,38272,34298,36031,0.954986,0.939886,1.000000,0.955873,0.924292
3,chrom,1_h_lr_0.0003_tie_True_norm_None,38272,34298,36060,0.903624,0.929285,1.000000,0.949566,0.906381
4,chrom,1_h_lr_0.005_tie_False_norm_None,38272,34298,35491,0.969464,0.960846,1.000000,0.961730,0.930233
5,chrom,1_h_lr_0.005_tie_True_norm_None,38272,34298,34637,0.976150,0.977647,1.000000,0.967637,0.945424
6,chrom,2_h_lr_0.0001_tie_False_norm_None,38272,34298,36465,0.860479,0.922323,1.000000,0.947792,0.906759
7,chrom,2_h_lr_0.0001_tie_True_norm_None,38272,34298,37708,0.834074,0.895527,1.000000,0.941464,0.889650
8,chrom,2_h_lr_0.0003_tie_False_norm_None,38272,34298,36016,0.960317,0.945408,1.000000,0.954140,0.920186
9,chrom,2_h_lr_0.0003_tie_True_norm_None,38272,34298,36121,0.913766,0.928480,1.000000,0.949566,0.908309
10,chrom,2_h_lr_0.005_tie_False_norm_None,38272,34298,36324,0.788382,0.911468,1.000000,0.929308,0.868573
11,chrom,2_h_lr_0.005_tie_True_norm_None,38272,34298,34682,0.967889,0.966479,1.000000,0.960927,0.929822
12,chrom,3_h_lr_0.0001_tie_False_norm_None,38272,34298,37025,0.832942,0.909531,1.000000,0.944714,0.897607
13,chrom,3_h_lr_0.0001_tie_True_norm_None,38272,34298,38116,0.828972,0.895221,1.000000,0.944714,0.895221
14,chrom,3_h_lr_0.0003_tie_False_norm_None,38272,34298,36004,0.968860,0.946540,1.000000,0.954560,0.927926
15,chrom,3_h_lr_0.0003_tie_True_norm_None,38272,34298,35555,0.969485,0.961405,1.000000,0.956173,0.925045
16,chrom,3_h_lr_0.005_tie_False_norm_None,38272,34298,35915,0.915458,0.923966,1.000000,0.946854,0.901176
17,chrom,3_h_lr_0.005_tie_True_norm_None,38272,34298,34946,0.979379,0.967480,1.000000,0.964240,0.940885
18,plasmid,1_h_lr_0.0001_tie_False_norm_None,38272,5365,5165,0.907061,0.645161,0.645658,0.536585,0.857738
19,plasmid,1_h_lr_0.0001_tie_True_norm_None,38272,5365,10447,0.838494,0.254237,0.878671,0.434783,0.707713
20,plasmid,1_h_lr_0.0003_tie_False_norm_None,38272,5365,5534,0.958970,0.761287,0.826290,0.711982,0.895436
21,plasmid,1_h_lr_0.0003_tie_True_norm_None,38272,5365,5339,0.918658,0.769231,0.750000,0.652482,0.880215
22,plasmid,1_h_lr_0.005_tie_False_norm_None,38272,5365,5643,0.975992,0.888889,0.862745,0.777269,0.910598
23,plasmid,1_h_lr_0.005_tie_True_norm_None,38272,5365,5672,0.977503,0.875000,0.892681,0.800000,0.934799
24,plasmid,2_h_lr_0.0001_tie_False_norm_None,38272,5365,7321,0.887963,0.333333,0.750000,0.470588,0.820405
25,plasmid,2_h_lr_0.0001_tie_True_norm_None,38272,5365,9106,0.845201,0.260870,0.836022,0.438487,0.747727
26,plasmid,2_h_lr_0.0003_tie_False_norm_None,38272,5365,5694,0.963887,0.828571,0.833333,0.751249,0.893684
27,plasmid,2_h_lr_0.0003_tie_True_norm_None,38272,5365,4866,0.905331,0.677419,0.638125,0.625000,0.862669
28,plasmid,2_h_lr_0.005_tie_False_norm_None,38272,5365,4795,0.795032,0.428571,0.313043,0.375000,0.814977
29,plasmid,2_h_lr_0.005_tie_True_norm_None,38272,5365,7500,0.971156,0.755749,0.911336,0.750000,0.896346
30,plasmid,3_h_lr_0.0001_tie_False_norm_None,38272,5365,6877,0.858486,0.304348,0.672619,0.424242,0.797676
31,plasmid,3_h_lr_0.0001_tie_True_norm_None,38272,5365,8307,0.840536,0.242647,0.750000,0.405063,0.742396
32,plasmid,3_h_lr_0.0003_tie_False_norm_None,38272,5365,5627,0.974368,0.835145,0.870897,0.765674,0.896863
33,plasmid,3_h_lr_0.0003_tie_True_norm_None,38272,5365,4809,0.972081,0.902778,0.798810,0.727273,0.906673
34,plasmid,3_h_lr_0.005_tie_False_norm_None,38272,5365,4413,0.912114,0.867007,0.600598,0.612040,0.888106
35,plasmid,3_h_lr_0.005_tie_True_norm_None,38272,5365,6486,0.984484,0.827778,0.904545,0.798374,0.925580

In [4]:
second

,mol_type,method,contigs,real,predicted,auc,precision,recall,f1,accuracy
0,chrom,1_h_lr_0.0001_tie_False_norm_batch,38272,34298.0,35950.0,0.891321,0.936339,1.000000,0.951400,0.909991
1,chrom,1_h_lr_0.0001_tie_False_norm_layer,38272,34298.0,35143.0,0.968470,0.968881,1.000000,0.965868,0.946154
2,chrom,1_h_lr_0.0001_tie_True_norm_batch,38272,34298.0,37990.0,0.853244,0.894243,1.000000,0.942089,0.890965
3,chrom,1_h_lr_0.0001_tie_True_norm_layer,38272,34298.0,35463.0,0.949219,0.960655,1.000000,0.956009,0.925045
4,chrom,1_h_lr_0.0003_tie_False_norm_batch,38272,34298.0,35783.0,0.953146,0.952683,1.000000,0.953577,0.921435
...,...,...,...,...,...,...,...,...,...,...
67,plasmid,3_h_lr_0.0003_tie_True_norm_layer,38272,5365.0,6722.0,0.953351,0.723875,0.889566,0.688525,0.897761
68,plasmid,3_h_lr_0.005_tie_False_norm_batch,38272,5365.0,4329.0,0.872126,0.785714,0.404545,0.500000,0.856288
69,plasmid,3_h_lr_0.005_tie_False_norm_layer,38272,5365.0,6066.0,0.911438,0.513158,0.669399,0.500000,0.837537
70,plasmid,3_h_lr_0.005_tie_True_norm_batch,38272,5365.0,5489.0,0.985789,0.892857,0.846154,0.800000,0.933772
71,plasmid,3_h_lr_0.005_tie_True_norm_layer,38272,5365.0,37119.0,0.532938,0.158155,1.000000,0.345385,0.207168

In [5]:
third

,mol_type,method,contigs,real,predicted,auc,precision,recall,f1,accuracy
0,chrom,1_h_lr_0.001_tie_False_norm_None,38272,34298.0,35612.0,0.965336,0.954545,1.000000,0.962406,0.940885
1,chrom,1_h_lr_0.001_tie_False_norm_batch,38272,34298.0,35899.0,0.956816,0.943651,1.000000,0.959819,0.933768
2,chrom,1_h_lr_0.001_tie_False_norm_layer,38272,34298.0,36169.0,0.928489,0.940285,1.000000,0.953775,0.917765
3,chrom,1_h_lr_0.001_tie_True_norm_None,38272,34298.0,35289.0,0.963990,0.957445,1.000000,0.960861,0.928474
4,chrom,1_h_lr_0.001_tie_True_norm_batch,38272,34298.0,35399.0,0.964034,0.965507,1.000000,0.962102,0.939221
...,...,...,...,...,...,...,...,...,...,...
67,plasmid,3_h_lr_0.003_tie_False_norm_batch,38272,5365.0,5331.0,0.813961,0.574176,0.434286,0.469136,0.839646
68,plasmid,3_h_lr_0.003_tie_False_norm_layer,38272,5365.0,6198.0,0.958531,0.759494,0.843077,0.717143,0.892642
69,plasmid,3_h_lr_0.003_tie_True_norm_None,38272,5365.0,4986.0,0.973710,0.866026,0.862745,0.784314,0.922065
70,plasmid,3_h_lr_0.003_tie_True_norm_batch,38272,5365.0,5115.0,0.966984,0.872549,0.879655,0.797590,0.931971
71,plasmid,3_h_lr_0.003_tie_True_norm_layer,38272,5365.0,5924.0,0.982819,0.808157,0.897368,0.777341,0.918762

In [7]:
merged = pd.concat([first,second,third])

In [8]:
merged

,mol_type,method,contigs,real,predicted,auc,precision,recall,f1,accuracy
0,chrom,1_h_lr_0.0001_tie_False_norm_None,38272,34298.0,36203.0,0.893120,0.926137,1.000000,0.947228,0.907294
1,chrom,1_h_lr_0.0001_tie_True_norm_None,38272,34298.0,38218.0,0.847683,0.890142,1.000000,0.940428,0.887556
2,chrom,1_h_lr_0.0003_tie_False_norm_None,38272,34298.0,36031.0,0.954986,0.939886,1.000000,0.955873,0.924292
3,chrom,1_h_lr_0.0003_tie_True_norm_None,38272,34298.0,36060.0,0.903624,0.929285,1.000000,0.949566,0.906381
4,chrom,1_h_lr_0.005_tie_False_norm_None,38272,34298.0,35491.0,0.969464,0.960846,1.000000,0.961730,0.930233
...,...,...,...,...,...,...,...,...,...,...
67,plasmid,3_h_lr_0.003_tie_False_norm_batch,38272,5365.0,5331.0,0.813961,0.574176,0.434286,0.469136,0.839646
68,plasmid,3_h_lr_0.003_tie_False_norm_layer,38272,5365.0,6198.0,0.958531,0.759494,0.843077,0.717143,0.892642
69,plasmid,3_h_lr_0.003_tie_True_norm_None,38272,5365.0,4986.0,0.973710,0.866026,0.862745,0.784314,0.922065
70,plasmid,3_h_lr_0.003_tie_True_norm_batch,38272,5365.0,5115.0,0.966984,0.872549,0.879655,0.797590,0.931971
71,plasmid,3_h_lr_0.003_tie_True_norm_layer,38272,5365.0,5924.0,0.982819,0.808157,0.897368,0.777341,0.918762

In [10]:
only_plasmid = merged[merged['mol_type'] == "plasmid"]

In [11]:
only_plasmid

,mol_type,method,contigs,real,predicted,auc,precision,recall,f1,accuracy
18,plasmid,1_h_lr_0.0001_tie_False_norm_None,38272,5365.0,5165.0,0.907061,0.645161,0.645658,0.536585,0.857738
19,plasmid,1_h_lr_0.0001_tie_True_norm_None,38272,5365.0,10447.0,0.838494,0.254237,0.878671,0.434783,0.707713
20,plasmid,1_h_lr_0.0003_tie_False_norm_None,38272,5365.0,5534.0,0.958970,0.761287,0.826290,0.711982,0.895436
21,plasmid,1_h_lr_0.0003_tie_True_norm_None,38272,5365.0,5339.0,0.918658,0.769231,0.750000,0.652482,0.880215
22,plasmid,1_h_lr_0.005_tie_False_norm_None,38272,5365.0,5643.0,0.975992,0.888889,0.862745,0.777269,0.910598
...,...,...,...,...,...,...,...,...,...,...
67,plasmid,3_h_lr_0.003_tie_False_norm_batch,38272,5365.0,5331.0,0.813961,0.574176,0.434286,0.469136,0.839646
68,plasmid,3_h_lr_0.003_tie_False_norm_layer,38272,5365.0,6198.0,0.958531,0.759494,0.843077,0.717143,0.892642
69,plasmid,3_h_lr_0.003_tie_True_norm_None,38272,5365.0,4986.0,0.973710,0.866026,0.862745,0.784314,0.922065
70,plasmid,3_h_lr_0.003_tie_True_norm_batch,38272,5365.0,5115.0,0.966984,0.872549,0.879655,0.797590,0.931971
71,plasmid,3_h_lr_0.003_tie_True_norm_layer,38272,5365.0,5924.0,0.982819,0.808157,0.897368,0.777341,0.918762

In [12]:
parts = only_plasmid["method"].str.split("_", expand=True)

heads = parts[0].astype(int)
lr = parts[3].astype(float)
tie = parts[5] == "True"
norm = parts[7]

only_plasmid.insert(2, "heads", heads)
only_plasmid.insert(3, "learning_rate", lr)
only_plasmid.insert(4, "tie", tie)
only_plasmid.insert(5, "normalization", norm)

In [13]:
only_plasmid

,mol_type,method,heads,learning_rate,tie,normalization,contigs,real,predicted,auc,precision,recall,f1,accuracy
18,plasmid,1_h_lr_0.0001_tie_False_norm_None,1,0.0001,False,None,38272,5365.0,5165.0,0.907061,0.645161,0.645658,0.536585,0.857738
19,plasmid,1_h_lr_0.0001_tie_True_norm_None,1,0.0001,True,None,38272,5365.0,10447.0,0.838494,0.254237,0.878671,0.434783,0.707713
20,plasmid,1_h_lr_0.0003_tie_False_norm_None,1,0.0003,False,None,38272,5365.0,5534.0,0.958970,0.761287,0.826290,0.711982,0.895436
21,plasmid,1_h_lr_0.0003_tie_True_norm_None,1,0.0003,True,None,38272,5365.0,5339.0,0.918658,0.769231,0.750000,0.652482,0.880215
22,plasmid,1_h_lr_0.005_tie_False_norm_None,1,0.0050,False,None,38272,5365.0,5643.0,0.975992,0.888889,0.862745,0.777269,0.910598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,plasmid,3_h_lr_0.003_tie_False_norm_batch,3,0.0030,False,batch,38272,5365.0,5331.0,0.813961,0.574176,0.434286,0.469136,0.839646
68,plasmid,3_h_lr_0.003_tie_False_norm_layer,3,0.0030,False,layer,38272,5365.0,6198.0,0.958531,0.759494,0.843077,0.717143,0.892642
69,plasmid,3_h_lr_0.003_tie_True_norm_None,3,0.0030,True,None,38272,5365.0,4986.0,0.973710,0.866026,0.862745,0.784314,0.922065
70,plasmid,3_h_lr_0.003_tie_True_norm_batch,3,0.0030,True,batch,38272,5365.0,5115.0,0.966984,0.872549,0.879655,0.797590,0.931971
71,plasmid,3_h_lr_0.003_tie_True_norm_layer,3,0.0030,True,layer,38272,5365.0,5924.0,0.982819,0.808157,0.897368,0.777341,0.918762

In [15]:
only_plasmid.to_csv("/home/buchalova/school/plASgraph2/results/all_experiments.csv",index=False)